//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.10.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace ReSharperPlugin.SampleRiderPlugin
{
  
  
  /// <summary>
  /// <p>Generated from: SampleModel.kt:9</p>
  /// </summary>
  public class SampleModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IViewableProperty<string> SomeProp => _SomeProp;
    [NotNull] public IViewableProperty<string> MethodInfo => _MethodInfo;
    
    /// <summary>
    /// Refresh
    /// </summary>
    [NotNull] public ISource<bool> Refresh => _Refresh;
    [NotNull] public IRdEndpoint<Unit, bool> HasMethod => _HasMethod;
    
    //private fields
    [NotNull] private readonly RdProperty<string> _SomeProp;
    [NotNull] private readonly RdProperty<string> _MethodInfo;
    [NotNull] private readonly RdSignal<bool> _Refresh;
    [NotNull] private readonly RdCall<Unit, bool> _HasMethod;
    
    //primary constructor
    private SampleModel(
      [NotNull] RdProperty<string> someProp,
      [NotNull] RdProperty<string> methodInfo,
      [NotNull] RdSignal<bool> refresh,
      [NotNull] RdCall<Unit, bool> hasMethod
    )
    {
      if (someProp == null) throw new ArgumentNullException("someProp");
      if (methodInfo == null) throw new ArgumentNullException("methodInfo");
      if (refresh == null) throw new ArgumentNullException("refresh");
      if (hasMethod == null) throw new ArgumentNullException("hasMethod");
      
      _SomeProp = someProp;
      _MethodInfo = methodInfo;
      _Refresh = refresh;
      _HasMethod = hasMethod;
      _SomeProp.OptimizeNested = true;
      _MethodInfo.OptimizeNested = true;
      BindableChildren.Add(new KeyValuePair<string, object>("someProp", _SomeProp));
      BindableChildren.Add(new KeyValuePair<string, object>("methodInfo", _MethodInfo));
      BindableChildren.Add(new KeyValuePair<string, object>("refresh", _Refresh));
      BindableChildren.Add(new KeyValuePair<string, object>("hasMethod", _HasMethod));
    }
    //secondary constructor
    internal SampleModel (
    ) : this (
      new RdProperty<string>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString),
      new RdProperty<string>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString),
      new RdSignal<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdCall<Unit, bool>(JetBrains.Rd.Impl.Serializers.ReadVoid, JetBrains.Rd.Impl.Serializers.WriteVoid, JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool)
    ) {}
    //deconstruct trait
    //statics
    
    
    
    protected override long SerializationHash => -262870201225251640L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(JetBrains.Rider.Model.IdeRoot), JetBrains.Rider.Model.IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("SampleModel (");
      using (printer.IndentCookie()) {
        printer.Print("someProp = "); _SomeProp.PrintEx(printer); printer.Println();
        printer.Print("methodInfo = "); _MethodInfo.PrintEx(printer); printer.Println();
        printer.Print("refresh = "); _Refresh.PrintEx(printer); printer.Println();
        printer.Print("hasMethod = "); _HasMethod.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionSampleModelEx
   {
    public static SampleModel GetSampleModel(this JetBrains.Rider.Model.Solution solution)
    {
      return solution.GetOrCreateExtension("sampleModel", () => new SampleModel());
    }
  }
}
